name: Daily Update
on:
  schedule: [{cron: '30 2 * * *'}] # 8:00 AM IST
  workflow_dispatch: # This allows the "Manual Run" button
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: {contents: write}
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python fetch_data.py
      - run: |
          git config --global user.name 'Bot'
          git config --global user.email 'bot@github.com'
          git add .
          git commit -m "Update" || exit 0
          git push
